- CONTRIBUTING.md
- README.md
Text fixes on README & Contributing.
> FE-515 Minor fixes on README & Contributing

- app/src/main/java/com/weatherxm/ui/deviceeditlocation/DeviceEditLocationActivity.kt
- app/src/main/res/layout/activity_device_edit_location.xml
- app/src/main/res/values/strings.xml
We need more explanation at the station relocation feature about what will happen to the rewards.
1. Changed the warning box's text
2. Moved the warning box above the toggle
3. Implemented the new view on a successful station relocation
Use the station relocation feature and make sure everything is OK text-wise.
> FE-590 Update station relocation messages

- app/src/main/java/com/weatherxm/data/ApiModels.kt
The new API models needed for the updated rewards response.
Created `RewardsResponse` , `Reward` and `RewardsTimelineEntry` data classes.
Ensure that the models match the spec's one.
> FE-619 Create new data class for the updated rewards response

- app/src/main/java/com/weatherxm/data/ApiModels.kt
The new API models needed for the updated rewards timeline response.
Created `RewardsTimelineResponse`.
Ensure that the models match the spec's one.
> FE-634 Create data class for the new API model of the rewards timeline

- app/src/local/assets/mock_files/get_device_reward_details.json
- app/src/main/java/com/weatherxm/data/ApiModels.kt
- app/src/main/java/com/weatherxm/data/datasource/RewardsDataSource.kt
- app/src/main/java/com/weatherxm/data/network/ApiService.kt
- app/src/main/java/com/weatherxm/data/repository/RewardsRepository.kt
- app/src/main/java/com/weatherxm/ui/common/UIModels.kt
The new API models needed for the reward details response and the respective DataSource & Repository functions.
Created `RewardDetails`, `BaseReward`, `BoostRewards`, `BoostReward` models and `getRewardDetails` function.
Ensure that the models match the spec's one.
> FE-650 Create data model and datasource & repository functions

- app/src/main/java/com/weatherxm/data/network/ApiService.kt
Integrate new rewards endpoints.
Replace `/tokens` with `/rewards` endpoints.
Run a dev build and ensure everything is OK.
> FE-668 Integrate new reward endpoints

- app/src/main/java/com/weatherxm/ui/preferences/PreferenceFragment.kt
- app/src/main/java/com/weatherxm/util/Analytics.kt
Analytics on survey and research panel click on preferences.
Added 2 `SELECT_CONTENT`.
> FE-710 Analytics on survey and research panel click

- app/src/main/java/com/weatherxm/ui/cellinfo/CellInfoActivity.kt
- app/src/main/java/com/weatherxm/util/Analytics.kt
- app/src/main/res/layout/activity_cell_info.xml
- app/src/main/res/layout/view_line_chart.xml
- app/src/main/res/layout/view_profile_item_card.xml
- app/src/main/res/menu/cell_details_menu.xml
- app/src/main/res/values/company_info.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_widget.xml
Updated cell header.
- Added the respective XML components in the Cell's layout
- Added the respective functionality in `CellInfoActivity`
- Removed 3 excessive chip styles
Try either a cell with online stations either a cell with offline only and make sure info is represented properly.
> FE-705 Feature/cell stats

- app/build.gradle.kts
- gradle/libs.versions.toml
Upgrade Kotlin to 1.9.23.
Upgrade:
```
kotlin-android-plugin = "1.9.23"
kotlin-parcelize-plugin = "1.9.23"
ksp-plugin = "1.9.23-1.0.19"
```
Also updated `kotlinCompilerExtensionVersion = "1.5.11"` .
Ensure that the project builds successfully.
> Upgrade Kotlin

- app/src/main/res/layout/activity_rewards_list.xml
- app/src/main/res/layout/view_reward_issue.xml
- app/src/main/res/values/strings.xml
1. Change empty rewards text
2. Change timeline top bar's background to `colorSurface`
3. Change elevation in reward issue card
Ensure everything looks OK with the 3 changes in the code below.
> FE-766 Minor UI fixes

- app/build.gradle.kts
Upgrade versionCode and versionNumber to 3.9.0
> Upgrade versionCode and versionNumber to 3.9.0

- app/src/main/java/com/weatherxm/ui/devicealerts/DeviceAlertsActivity.kt
- app/src/main/java/com/weatherxm/ui/devicedetails/DeviceDetailsActivity.kt
- app/src/main/java/com/weatherxm/ui/home/devices/DevicesFragment.kt
- app/src/main/java/com/weatherxm/util/Analytics.kt
Integrate analytics for low battery feature.
Ensure that the changes match [the spec](https://linear.app/weatherxm/issue/FE-780/low-battery-analytics-integration).
> FE-780 Feature/low battery analytics

- app/src/main/res/values/styles_widget.xml
Fix Tonal button background tint.
Replaced in the style `buttonTint` with `backgroundTint`
Ensure the "View All" in alerts looks as the design.
> FE-799 Fix Tonal button background tint

- .github/workflows/production-distribution.yml
Action failed [here](https://github.com/WeatherXM/wxm-android/actions/runs/8735058479/job/23967034171).
Fixed a typo and added the actual path to the `.aab`
> FE-806 Fixes on distribution workflow

- .github/workflows/production-distribution.yml
> Fix releaseFiles path

- .github/workflows/production-distribution.yml
`com.weatherxm.com` -> `com.weatherxm.app` 😞
> Fix package name

- app/src/main/java/com/weatherxm/ui/devicedetails/forecast/ForecastFragment.kt
- app/src/main/java/com/weatherxm/ui/deviceforecast/ForecastDetailsActivity.kt
- app/src/main/java/com/weatherxm/util/Analytics.kt
Track the respective forecast analytics per the spec. Removed some unused key/values in Analytics.
Ensure that the code changes match the spec's requirement on analytics.
> FE-784 Forecast Analytics

- app/src/main/java/com/weatherxm/ui/common/Views.kt
- app/src/main/java/com/weatherxm/ui/devicedetails/DeviceDetailsActivity.kt
- app/src/main/java/com/weatherxm/usecases/DeviceDetailsUseCaseImpl.kt
Include offline alert in count
Use all alerts in the counting chip and not the filtered ones.
Testing code has been included to show all 3 different issues in Device Details so just ensure that "3 issues" is visible.
> FE-839 Include offline alert in count

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/weatherxm/data/Modules.kt
- app/src/main/java/com/weatherxm/ui/Navigator.kt
- app/src/main/java/com/weatherxm/ui/connectwallet/ConnectWalletActivity.kt
- app/src/main/res/values/messages.xml
- gradle/libs.versions.toml
Replaced the current barcode scanner with GmsBarcodeScanner.
Cannot scan Gnosis Safe wallet QR code address. Current barcode scanner does nothing.
Replaced the old barcode scanner with the one from Google Play Services.
Edit/add a wallet by scanning a Gnosis Safe wallet address QR code.
N/A
**This PR is non-exhaustive. It's only a draft proof-of-concept.** It's not handling cancellation and error and it hasn't been tested for compatibility with multiple android devices. Also, it doesn't replace the barcode scanner globally, which may still used in other use cases (e.g. scanning a M5's QR code for claiming).
> FE-822 Use GmsBarcodeScanner for wallet address QR code scanning

- app/src/main/java/com/weatherxm/ui/Navigator.kt
- app/src/main/java/com/weatherxm/ui/claimdevice/helium/result/ClaimHeliumResultFragment.kt
- app/src/main/java/com/weatherxm/ui/claimdevice/selectstation/SelectStationTypeActivity.kt
- app/src/main/java/com/weatherxm/ui/claimdevice/wifi/result/ClaimWifiResultFragment.kt
- app/src/main/res/layout/fragment_claim_wifi_result.xml
- app/src/main/res/values/strings.xml
Minor changes in the claiming result screen
Just made some minor text changes.
Try some claiming tests in M5 and D1 and ensure everything is OK.
> FE-834 Feature/refactor claim result

- app/build.gradle.kts
Print tags when getting version name
Just a bunch of `println`.
> Print tags when getting version name

- app/src/main/java/com/weatherxm/data/bluetooth/BluetoothConnectionManager.kt
- app/src/main/java/com/weatherxm/ui/components/BaseInterface.kt
Research about crashes and catch those that can be caught (in order not to crash)
- Catch `ConnectionLostException` in `peripheral.disconnect()`
- Catch `BluetoothDevice == null` when using `BluetoothDevice.name`
- Catch `IllegalArgumentException` in `Snackbar.make` so it doesn't crash and added more logs in order to better understand the cause of it.
Nothing to be tested here I think. These are rare cases where I couldn't reproduce them as well.
> FE-890 Feature/catch rare crashes

- app/src/main/java/com/weatherxm/ui/rewardboosts/RewardBoostActivity.kt
- app/src/main/res/values/messages.xml
Boost Reward --> Reward Boost in the error's  title
> FE-886 Fix reward boost error's title 

- app/src/main/java/com/weatherxm/ui/claimdevice/helium/frequency/ClaimHeliumFrequencyFragment.kt
- app/src/main/java/com/weatherxm/ui/components/HeliumSetFrequencyView.kt
- app/src/main/java/com/weatherxm/ui/devicesettings/changefrequency/ChangeFrequencyActivity.kt
- app/src/main/res/layout/activity_change_frequency_station.xml
- app/src/main/res/layout/fragment_claim_helium_frequency.xml
- app/src/main/res/layout/view_helium_set_frequency.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
We have same UI components (almost duplicate .XML files) for setting frequency on claiming and for changing frequency so I created a new `HeliumSetFrequency` component.
- Created the `HeliumSetFrequency` component with the respective functions in order to set some listeners on specific actions
- Replaced the duplicate code in `ChangeFrequencyActivity` and `ClaimHeliumFrequencyFragment` and its respective `.xml` files with that new component
Ensure that both screens look OK.
> FE-889 Feature/optimize change frequency code

- app/src/main/java/com/weatherxm/ui/claimdevice/helium/ClaimHeliumActivity.kt
- app/src/main/java/com/weatherxm/ui/claimdevice/helium/ClaimHeliumViewModel.kt
- app/src/main/java/com/weatherxm/ui/claimdevice/helium/frequency/ClaimHeliumFrequencyFragment.kt
- app/src/main/java/com/weatherxm/ui/claimdevice/helium/pair/ClaimHeliumPairFragment.kt
- app/src/main/java/com/weatherxm/ui/claimdevice/helium/reset/ClaimHeliumResetFragment.kt
- app/src/main/java/com/weatherxm/ui/common/Views.kt
- app/src/main/java/com/weatherxm/ui/components/BleActionFlowView.kt
- app/src/main/java/com/weatherxm/ui/components/HeliumSetFrequencyView.kt
- app/src/main/java/com/weatherxm/ui/devicesettings/changefrequency/ChangeFrequencyActivity.kt
- app/src/main/res/layout/activity_change_frequency_station.xml
- app/src/main/res/layout/fragment_claim_helium_frequency.xml
- app/src/main/res/layout/fragment_claim_helium_pair.xml
- app/src/main/res/layout/fragment_claim_helium_reset.xml
- app/src/main/res/layout/fragment_claim_helium_result.xml
- app/src/main/res/layout/list_item_scanned_device.xml
- app/src/main/res/layout/view_ble_action_flow.xml
- app/src/main/res/layout/view_helium_set_frequency.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Refactor the helium logic and migrate it with the newly implemented M5/D1 logic.
- UI fixes here and there in all steps to ensure that the texts/margins/fonts/colors etc are the same as the designs
Ensure that everything is OK in the Helium's claiming flow.
> FE-884 Update Helium's claiming flow to the new designs

- app/src/main/assets/countries_information.json
Updated some Helium frequencies based on [this](https://docs.helium.com/iot/lorawan-region-plans/) and [this](https://www.thethingsnetwork.org/docs/lorawan/frequencies-by-country/).
Use [Helium's table](https://docs.helium.com/iot/lorawan-region-plans/) and if it's a frequency we don't support (e.g. EU433) check the [TTN's one](www.thethingsnetwork.org/docs/lorawan/frequencies-by-country) and decide based on it.
Ensure that the changes look OK based on the "How" above.
> FE-891 Feature/update helium frequencies

- app/src/main/res/layout/view_charts.xml
- app/src/main/res/values/strings.xml
Just a replacement of the string.
> FE-898 Replace in highlighted part in charts the "Rate" with "Max Rate"

- app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt
- app/src/main/java/com/weatherxm/analytics/AnalyticsWrapper.kt
- app/src/main/java/com/weatherxm/analytics/FirebaseAnalyticsService.kt
- app/src/main/java/com/weatherxm/analytics/MixpanelAnalyticsService.kt
- app/src/main/java/com/weatherxm/ui/home/profile/ProfileFragment.kt
- app/src/main/java/com/weatherxm/ui/rewardsclaim/RewardsClaimActivity.kt
Capture some important KPIs (how many users started the claiming process and the result of it - success or failure).
- Track the ScreenView in the `onResume` at `RewardsClaimActivity`
- Based on the result of the claiming in `ProfileFragment` track a `VIEW_CONTENT` event containing the `STATE` (success or failure, for now) parameter.
Run a **release** flavor (not debug), enable analytics and ensure that events are logged properly.
> FE-900 Integrate some claiming flow analytics

- app/src/main/java/com/weatherxm/ui/claimdevice/selectstation/SelectStationTypeActivity.kt
- app/src/main/res/layout/activity_claim_select_station.xml
Just edited the `.xml` file.
Make sure the Pulse isn't there.
> FE-943 Hide Pulse from Select Station as it's not ready yet

- app/src/main/java/com/weatherxm/ui/claimdevice/location/ClaimLocationFragment.kt
- app/src/main/java/com/weatherxm/ui/claimdevice/wifi/preparegateway/ClaimWifiPrepareGatewayFragment.kt
- app/src/main/java/com/weatherxm/ui/components/BaseMapFragment.kt
- app/src/main/java/com/weatherxm/ui/devicesettings/DeviceSettingsActivity.kt
Fixed 2 issues reported by the product team, described in the respective [Linear issue](https://linear.app/weatherxm/issue/FE-962/improvements-for-android-via-product-testing-phase).
- Increased the default zoom level from 1 to 2 on Mapbox as it seems due to a library updated they treat differently now the "1" we had before showing the Globe.
- Used the `anchorView` in the snackbar in order to show it above the buttons and added ad `dismiss` button.
Ensure that both issues are fixed.
> FE-962 Feature/fix claiming

- app/src/main/java/com/weatherxm/ui/claimdevice/pulse/manualdetails/ClaimPulseManualDetailsFragment.kt
- app/src/main/java/com/weatherxm/ui/claimdevice/pulse/preparegateway/ClaimPulsePrepareGatewayFragment.kt
- app/src/main/res/layout/fragment_claim_pulse_manual_details.xml
Fix scanning Pulse barcode.
Fix scanning Pulse barcode by removing the "P" prefix and moving to next screen if successful
Ensure that scanning a valid barcode works correctly.
> FE-997 Fix scanning Pulse barcode

- .github/pull_request_template.md
Fix the different headings in each category and remove the screenshots section as we do not use it and each reviewer should run the PR locally to ensure everything is OK even UI-wise.
Not testable, just make sure the changes in the `pull_request_template.md` look OK.
> FE-1012 Update PR Template

- app/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
Update Kable library and sort them alphabetically
1. Ensure that the project builds successfully
2. Connect to a device via BLE and perform an operation (e.g. Reboot)
> FE-1015 Update Kable library and sort them alphabetically

- app/src/main/res/values/company_info.xml
Updated `d1_connect_wifi_instructional_video`
Make sure the correct Youtube video is shown: https://www.youtube.com/watch?v=D3rz1Y01Qhg
> FE-1047 Update D1 WiFi video

- app/src/main/java/com/weatherxm/ui/devicealerts/DeviceAlertsActivity.kt
- app/src/main/java/com/weatherxm/ui/devicedetails/current/CurrentFragment.kt
- app/src/main/java/com/weatherxm/ui/home/devices/DevicesFragment.kt
- app/src/main/res/values/company_info.xml
Fix some URLs missing and some deprecated.
Added the respective troubleshooting & low battery URLs for Pulse and added the respective code in some `when` statements and introduced the function `showOfflineAlert` in order to avoid repetitive code.
Just make sure the URLs used are working properly. We do not have a Pulse station so can't check it directly, just open the URL in the "Changelog" in a browser.
Contains also FE-1059 and the following URL updates:
1. https://docs.weatherxm.com/wallet/add-edit-wallet-address#how-to-create-wallet-on-metamask ---> https://docs.weatherxm.com/mobile-app/wallet/add-edit-wallet-address#how-to-create-wallet-on-metamask
2. https://docs.weatherxm.com/wifi-m5-bundle/m5-troubleshooting ---> https://docs.weatherxm.com/wxm-devices/m5/troubleshooting
3. …
> FE-1061 FE-1059 Feature/url fixes

- app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt
- app/src/main/java/com/weatherxm/ui/common/UIModels.kt
- app/src/main/java/com/weatherxm/ui/devicesettings/BaseDeviceSettingsViewModel.kt
- app/src/main/java/com/weatherxm/ui/devicesettings/helium/DeviceSettingsHeliumActivity.kt
- app/src/main/java/com/weatherxm/ui/devicesettings/helium/DeviceSettingsHeliumViewModel.kt
- app/src/main/java/com/weatherxm/ui/devicesettings/wifi/DeviceSettingsWifiActivity.kt
- app/src/main/java/com/weatherxm/ui/devicesettings/wifi/DeviceSettingsWifiViewModel.kt
- app/src/main/java/com/weatherxm/ui/rewarddetails/RewardDetailsActivity.kt
- app/src/main/java/com/weatherxm/ui/rewarddetails/RewardDetailsViewModel.kt
- app/src/main/java/com/weatherxm/ui/rewarddetails/RewardSplitDialogFragment.kt
- app/src/main/res/layout/activity_device_settings_helium.xml
- app/src/main/res/layout/activity_device_settings_wifi.xml
Integrate Analytics in Reward Splits.
Added the respective `USER_ACTION` and `VIEW_CONTENT` based on our Analytics sheet. Created the functions `handleSplitRewards` in all different activities that handle listeners and analytics in the activities.
Navigate through all different options and ensure everything is logged properly on Analytics:
1. `reward split = true AND stakeholder = true`
2. `reward split = true AND stakeholder = false`
3. `reward split = false AND stakeholder = true`
4. `reward split = false AND stakeholder = false`
Add any other context about the PR here or remove this section.
> FE-1095 Feature/reward split analytics

- app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt
- app/src/main/java/com/weatherxm/ui/components/WeatherMeasurementCardView.kt
- app/src/main/java/com/weatherxm/ui/devicedetails/forecast/DailyForecastAdapter.kt
- app/src/main/java/com/weatherxm/ui/devicedetails/forecast/ForecastFragment.kt
- app/src/main/java/com/weatherxm/ui/devicedetails/forecast/TemperatureBarExplanationDialogFragment.kt
- app/src/main/java/com/weatherxm/ui/deviceforecast/ForecastDetailsActivity.kt
- app/src/main/java/com/weatherxm/util/Charts.kt
- app/src/main/res/layout/activity_forecast_details.xml
- app/src/main/res/layout/view_line_chart.xml
- app/src/main/res/layout/view_weather_measurement_card.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/palette.xml
Station Details - Forecast Details improvements
- Updated `WeatherMeasurementCardView` component which reflects the measurement view in the daily card in the forecast details screen, to have the new UI and added it respective in a new daily card in the forecast details screen
- Created two new colors for the charts `chart_primary_line`, `chart_secondary_line` which we use for the chart lines in the forecast and history charts.
1. Ensure that the new screen looks OK based on the proposed changes.
2. Make sure the chart coloring updates are reflected in the History screen as well.
> FE-1127 Feature/forecast details improvements

- .github/workflows/on-main-firebase-distribution.yml
Action failed: https://github.com/WeatherXM/wxm-android/actions/runs/10941078515/job/30374901980
Fix coverage report on main by including it in the main job.
> Fix coverage report on main by including it in the main job.

- app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt
- app/src/main/java/com/weatherxm/ui/devicesrewards/DeviceRewardsAdapter.kt
- app/src/main/java/com/weatherxm/ui/devicesrewards/DevicesRewardsActivity.kt
- app/src/main/java/com/weatherxm/ui/home/devices/DevicesFragment.kt
Stations Reward screen - Analytics events
Added the 3 events per the spec.
Ensure that events are logged properly when needed.
> FE-1153 Feature/analytics for reward analytics

- app/src/main/java/com/weatherxm/data/Modules.kt
Fix deprecated imports of Koin's viewModel.
Just changed the import package to the updated.
Ensure the project builds successfully.
> FE-1167 Fix deprecated imports of Koin's viewModel

- app/build.gradle.kts
- app/src/main/java/com/weatherxm/analytics/FirebaseAnalyticsService.kt
- app/src/main/java/com/weatherxm/analytics/MixpanelAnalyticsService.kt
- app/src/test/java/com/weatherxm/analytics/AnalyticsWrapperTest.kt
- app/src/test/java/com/weatherxm/analytics/AnalyticsWrapperTestCallVerifier.kt
- app/src/test/java/com/weatherxm/analytics/FirebaseAnalyticsServiceTest.kt
- app/src/test/java/com/weatherxm/analytics/MixpanelAnalyticsServiceTest.kt
- gradle/libs.versions.toml
Missing unit tests for analytics services.
- Created `FirebaseAnalyticsServiceTest`
- Created `MixpanelAnalyticsServiceTest`
- Created some missing tests regarding the `trackEventFailure` in `AnalyticsWrapper`
Ensure that the unit tests have a 100% success rate (can be found as a workflow run in this PR).
> FE-1164 Unit Tests for Analytics Services

- app/src/main/res/layout/view_chart_tooltip.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/palette.xml
Fix colors in tooltip in dark mode and light mode.
Use the new colors per the design.
Ensure the tooltip looks the same as the design in light and dark theme.
> FE-1168 Fix colors in tooltip

- app/src/main/java/com/weatherxm/data/datasource/DeviceOTADataSource.kt
- app/src/main/java/com/weatherxm/data/datasource/UserPreferenceDataSource.kt
- app/src/main/java/com/weatherxm/data/repository/UserPreferencesRepository.kt
- app/src/main/java/com/weatherxm/data/services/CacheService.kt
- app/src/test/java/com/weatherxm/TestConfig.kt
- app/src/test/java/com/weatherxm/data/datasource/DeviceOTADataSourceTest.kt
- app/src/test/java/com/weatherxm/data/datasource/UserPreferenceDataSourceTest.kt
- app/src/test/java/com/weatherxm/data/repository/UserPreferencesRepositoryTest.kt
- app/src/test/java/com/weatherxm/data/services/CacheServiceTest.kt
- app/src/test/java/com/weatherxm/data/services/InMemoryTest.kt
- app/src/test/java/com/weatherxm/data/services/PrefsSingleVarTest.kt
- app/src/test/java/com/weatherxm/data/services/PrefsStringEitherTest.kt
Unit Tests for the `CacheService`.
Added a unit test for each different function and created some helper classes in order to improve code readibility.
Ensure that the unit tests have a 100% success rate (can be found as a workflow run in this PR).
> FE-1174 Feature/unit tests cache service

- app/src/test/java/com/weatherxm/util/GeocoderCompatTest.kt
There were two tests missing and marked as `TODO`.
Created those tests.
Ensure that the unit tests have a 100% success rate (can be found as a workflow run in this PR).
> FE-1181 Create the last two tests for Geocoder Compat

- app/src/main/java/com/weatherxm/util/Validator.kt
- app/src/main/res/layout/view_edit_name.xml
- app/src/test/java/com/weatherxm/util/ValidatorTest.kt
Support a friendly name of up to 64 chars
Just changed the regex and the unit tests.
Ensure that up to 64 chars are allowed.
> FE-1171 Support a friendly name of up to 64 chars

- app/src/main/res/layout/activity_device_details.xml
- app/src/main/res/layout/fragment_device_details_forecast.xml
Some fixes in the layout file on some components that caused the errors.
Just ensure that when scrolling the navigation bar at the bottom doesn't hide any contents at the end of the scrolling (e.g. at the last element in the daily forecast list)
> FE-1303 Fix navigation bar hiding content in Device Details

- app/src/test/java/com/weatherxm/ui/common/DeviceTotalRewardDetailsTest.kt
Fix unit test using unresolved reference.
> Fix unit test using unresolved reference.

- app/src/main/java/com/weatherxm/ui/common/Views.kt
- app/src/main/java/com/weatherxm/ui/devicealerts/DeviceAlertsAdapter.kt
- app/src/main/res/values/strings.xml
1. Replace "Station Inactive" with "Inactive"
2. The color on the last seen chip is colored filled when inactive
Replaced "Station Inactive" with "Inactive" and fixed the chip color on inactive last seen status
Ensure that both issues are fixed.
> FE-1372 Minor fixes on 4.3.0

- app/src/main/res/values/strings.xml
Update the message of Low Battery Alert
Used the new message.
Ensure the new message shows up in Device's Alerts on the specific case of Low Battery.
> FE-1328 Update the message of Low Battery Alert

- app/build.gradle.kts
- app/src/main/java/com/weatherxm/ui/photoverification/gallery/PhotoGalleryViewModel.kt
- app/src/main/java/com/weatherxm/usecases/StationSettingsUseCaseImpl.kt
- app/src/test/java/com/weatherxm/data/datasource/DevicePhotoDataSourceTest.kt
- app/src/test/java/com/weatherxm/data/repository/DevicePhotoRepositoryTest.kt
- app/src/test/java/com/weatherxm/ui/devicesettings/wifi/DeviceSettingsWifiViewModelTest.kt
- app/src/test/java/com/weatherxm/ui/photoverification/gallery/PhotoGalleryViewModelTest.kt
- app/src/test/java/com/weatherxm/ui/photoverification/intro/PhotoVerificationIntroViewModelTest.kt
- app/src/test/java/com/weatherxm/usecases/DevicePhotoUseCaseTest.kt
Unit Tests for the "Station Photo Verification" feature till this point.
Introduced new unit tests for the data source, the repository, the usecase and the view models.
Just make sure the tests have 100% success rate.
> Unit tests for station photo verification flow

- app/src/main/java/com/weatherxm/ui/devicesettings/DevicePhotosView.kt
- app/src/main/java/com/weatherxm/ui/photoverification/gallery/PhotoGalleryActivity.kt
- app/src/main/java/com/weatherxm/ui/photoverification/upload/PhotoUploadActivity.kt
Issues found by QA:
1. Subtitle always visible when photos > 2
2. Exit prompt was checking the total photos and not the remote ones
1. Show subtitle only when `total_photos < 2`
2. Show exit prompt only when `remote_photos < 2`
Ensure both issues are fixed.
> FE-1559 FE-1542 FE-1537 Fixes on Photo Verification

- app/src/main/java/com/weatherxm/data/Modules.kt
- app/src/main/java/com/weatherxm/ui/claimdevice/location/ClaimLocationFragment.kt
- app/src/main/java/com/weatherxm/ui/claimdevice/result/ClaimResultFragment.kt
- app/src/main/java/com/weatherxm/ui/components/TooltipMarkerView.kt
- app/src/main/java/com/weatherxm/ui/devicedetails/DeviceDetailsActivity.kt
- app/src/main/java/com/weatherxm/ui/passwordprompt/PasswordPromptFragment.kt
- app/src/main/java/com/weatherxm/ui/startup/StartupActivity.kt
- app/src/main/java/com/weatherxm/util/Charts.kt
- app/src/main/res/layout/widget_current_weather_tile.xml
- app/src/main/res/layout/widget_preview_current_weather.xml
- app/src/main/res/layout/widget_preview_current_weather_detailed.xml
Fixed some deprecated code and remove some obsolete warnings
- Replaced `whenCreated` with `withCreated`
- Remove the not needed pending transation in `StartupActivity`
- Modified the `SearchEngine` in `Modules` to use the correct constructor
- Added missing package in `TooltipMarkerView`
- 
Just ensure the app builds correctly. Also check the following more explicitly:
1. The search functionality in the claiming flow works correctly
2. The password prompt (e.g. in the wallet screen) has the correct message.
> Fixed some deprecated code and remove some obsolete warnings

- app/src/main/java/com/weatherxm/ui/photoverification/gallery/PhotoGalleryActivity.kt
- app/src/main/res/layout/activity_photo_gallery.xml
- app/src/main/res/values/strings.xml
Show a helper text when max photos are reached.
Created the composable `MaxPhotosReached` and show/hide it depending on the current photos number.
Make sure it looks OK as per the design.
> Display helper text when max photos reached

- app/src/main/java/com/weatherxm/ui/components/PhotoUploadStateView.kt
- app/src/main/res/values/strings.xml
Some minor text fixes based on the latest product QA.
Make sure the new texts are OK.
> FE-1620 FE-1618 Text fixes on progress

- app/src/main/java/com/weatherxm/ui/home/devices/DevicesFragment.kt
- app/src/main/res/layout/fragment_devices.xml
Rename the label at the devices list from Total Earned -> Station Rewards
Just used the correct string resource and changed the view's ID respectively.
Make sure the new label is OK.
> Rename "Total earned" label

- app/src/main/java/com/weatherxm/ui/components/compose/HeaderView.kt
- app/src/main/java/com/weatherxm/ui/components/compose/InfoBannerView.kt
- app/src/main/java/com/weatherxm/ui/components/compose/PhotoUploadStateView.kt
- app/src/main/res/layout/activity_reward_details.xml
- app/src/main/res/layout/activity_rewards_list.xml
Some color issues and scrolling issues in the `HeaderView`, the rewards timeline and the info banner.
1. Fixed the color of the "close" button in the info banner
2. Fixed the color of the "info" button in the `HeaderView`
3. Fixed the scrolling of the rewards timeline (**needs to be tested against a PROD flavor**)
Ensure the above 3 look OK in both light & dark theme. For the info banner you could add `if (false)` in line 64 in `RemoteBannersDataSource.kt` 
Reused the `SmallText` and `MediumText` where it could in the `PhotoUploadStateView` as it has been forgotten to update it.
> Minor UI fixes

- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
Update Gradle version
Download the latest Android Studio Version - Meerkat 2024.3.1. Then build the project and ensure it's OK.
> Update Gradle version

- app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt
- app/src/main/java/com/weatherxm/ui/photoverification/gallery/PhotoGalleryActivity.kt
Analytics events for gallery screen
- `source` param for "Add Station Photo"
- Added "Remove Station Photo" events for gallyer and camer flow
Ensure the events are tracked properly
fixes fe-1790
> Analytics implementation for gallery updates

- app/src/main/java/com/weatherxm/ui/explorer/ExplorerMapFragment.kt
- app/src/main/java/com/weatherxm/ui/explorer/ExplorerViewModel.kt
- app/src/main/java/com/weatherxm/ui/explorer/MapLayerPickerDialogFragment.kt
- app/src/main/java/com/weatherxm/util/MapboxUtils.kt
- app/src/test/java/com/weatherxm/ui/explorer/ExplorerViewModelTest.kt
- app/src/test/java/com/weatherxm/util/MapboxUtilsTest.kt
Data Quality Score layer
- In `setMapLayer` run again the function `toPolygonAnnotationOptions` (which has changed to get the correct color now) on the current cells and trigger the new `fun onRedrawPolygons(): LiveData<List<PolygonAnnotationOptions>> = onRedrawPolygons`
- On the respective fragment, when the above function is triggered, clear the map and redraw the cells with the correct color (I tested it and its much faster clearing -> readding than updating the existing ones one by one)
Ensure that everything looks and works smoothly when changing layers.
> Create the data quality layer in the map

- app/src/main/java/com/weatherxm/ui/networkstats/NetworkStatsActivity.kt
- app/src/main/res/layout/activity_network_stats.xml
- app/src/main/res/values/strings.xml
Update $WXM Rewards card
- Updated the layout (added the right chevron and the text updates in the subtitle)
- Updated the activity code to open the reward mechanism URL
Ensure the UI looks OK. The functionality will come in a next PR.
> Update $WXM Rewards card

- .github/workflows/on-pr.yml
Fix the on-pr workflow
- Fixed the syntax errors by using the closing tags `}}`, replaced `success() || failure()` with `always()`
Not testable.
> Fix the on-pr workflow

- .github/workflows/on-pr.yml
Fix PR automated tasks, the previous one didn't work.
> Fix PR automated tasks

- app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt
- app/src/main/java/com/weatherxm/ui/networkstats/NetworkStatsActivity.kt
- app/src/main/java/com/weatherxm/ui/networkstats/UIModels.kt
- app/src/main/java/com/weatherxm/usecases/StatsUseCaseImpl.kt
- app/src/main/res/layout/activity_network_stats.xml
- app/src/main/res/values/strings.xml
The network health card.
- Integrated the new health card using the `NetworkStatsCardView` reusable component.
Ensure everything looks OK in the UI given the API response.
> Network health card

- app/src/main/java/com/weatherxm/ui/networkstats/growth/NetworkGrowthActivity.kt
Show total manufactured number of stations
> Show total manufactured number of stations

- app/src/main/java/com/weatherxm/ui/explorer/ExplorerViewModel.kt
More details on the Linear task with a screen recording there.
Better handling of calculating the stations in viewport when it comes to the antimeridian.
Ensure that the station count looks OK around the map and in the area specified around the antimeridian.
> Fix the stations in viewport calculation

- app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt
- app/src/main/java/com/weatherxm/ui/forecastdetails/ForecastDetailsActivity.kt
- app/src/main/java/com/weatherxm/ui/home/locations/LocationsFragment.kt
Integrate the new analytics as specified in the Linear task.
- Added a new screen view for location search
- Added a select content action when a location search result is clicked
- Added a view content event when a max saved locations error is shown to the user with the distinction authenticated vs non-authenticated.
Ensure the new events are integrated properly.
> Integrate the new analytics

- app/src/main/java/com/weatherxm/data/network/interceptor/AuthTokenAuthenticator.kt
Retry mechanism in refreshing the JWT token as an optimization in case of an API error.
Added a retry mechanism via recursion, with 2 retries max, the first one with a delay of 2 seconds, the second one with a delay of 5 seconds. If all fail, return the failure.
Not sure it's easy to test it. I would install the app, check the logs in Android Studio filtering for "JWT", check for the "expires" and just run the app again after the access token expires and ensure that the refresh takes place correctly.
> Retry mechanism in refreshing the JWT token

- app/src/main/java/com/weatherxm/data/datasource/QuestsDataSource.kt
- app/src/main/java/com/weatherxm/ui/Navigator.kt
- app/src/main/java/com/weatherxm/ui/components/compose/Texts.kt
- app/src/main/java/com/weatherxm/ui/questonboarding/QuestOnboardingActivity.kt
- app/src/main/java/com/weatherxm/ui/questonboarding/QuestOnboardingViewModel.kt
- app/src/main/java/com/weatherxm/ui/queststeps/QuestGenericStepActivity.kt
- app/src/main/java/com/weatherxm/ui/queststeps/QuestGenericStepViewModel.kt
- app/src/main/res/values/strings.xml
The environment sensors step
- Some UI fixes
- Handle the case of `ENABLE_ENVIRONMENT_SENSORS` properly
- Some refactoring and fixes mentioned in the previous PR
Ensure the sensors step works as expected 
fixes fe-1959
> Environment sensors step

- app/src/main/java/com/weatherxm/data/datasource/QuestsDataSource.kt
Calculate and update the earned tokens on the user document
On every fetch user request, we refresh the if tokens if needed
Ensure the earned tokens are updated properly
fixes fe-1965
> Update earned tokens in firestore

- app/src/main/java/com/weatherxm/ui/components/compose/EmptySavedLocationsView.kt
- app/src/main/java/com/weatherxm/ui/home/locations/LocationsFragment.kt
Clicking the "nothing saved yet" card opens the location search view
Added an `onClick` listener in `EmptySavedLocationsView` which opens the location serach view when clicking that box.
That a box click opens the location search view.
> Clicking the "nothing saved yet" card opens the location search view

- app/src/main/java/com/weatherxm/ui/onboarding/OnboardingActivity.kt
> Simple crossfade effect for onboarding background images

- app/src/local/assets/mock_files/get_user_device_rewards_summary.json
- app/src/main/java/com/weatherxm/data/models/ApiModels.kt
- app/src/main/java/com/weatherxm/ui/common/UIModels.kt
- app/src/main/java/com/weatherxm/ui/components/TooltipMarkerView.kt
- app/src/main/java/com/weatherxm/ui/devicesrewards/DeviceRewardsAdapter.kt
- app/src/main/java/com/weatherxm/ui/devicesrewards/DeviceRewardsBoostAdapter.kt
- app/src/main/java/com/weatherxm/ui/rewardboosts/RewardBoostActivity.kt
- app/src/main/java/com/weatherxm/ui/rewardboosts/RewardBoostDetailAdapter.kt
- app/src/main/java/com/weatherxm/ui/rewarddetails/RewardDetailsActivity.kt
- app/src/main/java/com/weatherxm/usecases/RewardsUseCase.kt
- app/src/main/java/com/weatherxm/util/Charts.kt
- app/src/main/res/layout/list_item_device_rewards.xml
- app/src/main/res/layout/view_chart_tooltip.xml
- app/src/main/res/values/palette.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/weatherxm/usecases/RewardsUseCaseTest.kt
Handle the correction/compensation boosts properly
Updated the `enum class` we had to support the `correction` code, and in the respective screens added handling for that code by using `code.startsWith("correction")` in order to handle it or not. Most of the code was copy-paste in how we handle the others already, and just used the correct variables.
Ensure that everything looks OK in:
1. Reward Analytics
2. Reward Details
3. Boost Detail
> Handle the correction/compensation boosts properly
