WeatherXM/wxm-android

app/src/main/AndroidManifest.xml, app/src/main/java/com/weatherxm/data/Modules.kt
Use `Firebase.crashlytics` per the official Firebase tutorial.
On `modules` instead of `FirebaseCrashlytics.getInstance()` use `Firebase.crashlytics`
=> FE-518 Use Firebase.crashlytics per the docs

app/src/main/java/com/weatherxm/data/DataModels.kt, app/src/main/java/com/weatherxm/service/MessagingService.kt, app/src/main/java/com/weatherxm/ui/Navigator.kt, app/src/main/java/com/weatherxm/ui/common/Contracts.kt, app/src/main/java/com/weatherxm/ui/components/EmptyView.kt, app/src/main/java/com/weatherxm/ui/startup/StartupActivity.kt, app/src/main/java/com/weatherxm/ui/startup/StartupState.kt, app/src/main/java/com/weatherxm/ui/startup/StartupViewModel.kt, app/src/main/java/com/weatherxm/ui/urlrouteractivity/UrlRouterActivity.kt, app/src/main/java/com/weatherxm/ui/urlrouteractivity/UrlRouterViewModel.kt, app/src/main/java/com/weatherxm/ui/widgets/RemoteViews.kt, app/src/main/java/com/weatherxm/util/Permissions.kt, app/src/main/res/layout/activity_url_router.xml
Integrate notifications in order to be able to show them to users.
1. Created `WXMRemoteMessage` which will be our `data class` for these messages
2. Created `enum class RemoteMessageType(val id: String, val publicName: String, val desc: String)` where `id` is the respective `type` custom value as agreed, `publicName` & `desc` are texts that will be visible in app-settings for informing the user what this channel is about.
3. Proper implementation of `onMessageReceived` in order to handle notifications when the app is on foreground
4. When the app is in the background, and the notification gets clicked, `StartupActivity` starts with notification-data in its `intent` so we handle it there and if the app opened due to a notification we open the `UrlRouterActivity`.
5. `UrlRouterActivity` …
=> FE-528 Integration of Notifications

.github/workflows/on-qa-firebase-distribution.yml, README.md
We need a way for the QA team to manually trigger releases whenever they want.
- Followed the guide [here](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) and added a `workflow_dispatch` GitHub Workflow, which takes as input the environment parameters (`production` or `development`), sets the respective environment and creates the respective release.
Not possible, based on [this](https://stackoverflow.com/a/74722590/5403137), the action needs to be on the `main` branch,
=> FE-555 Create a workflow_dispatch aka manual workflow to trigger a QA release

.github/workflows/on-qa-firebase-distribution.yml, README.md
We need to let the QA team who triggers the release to choose between `release` or `debug` build types.
Added:
```
buildType:
type: choice
description: 'Select between "release" and "debug" as build types.'
required: true
options:
- "release"
- "debug"
default: 'release'
```
And some `if` below to run the respective assemble and distribute commands.
Not possible until merged 😞
=> FE-566 Use as inputs the "release" & "debug" on the manual QA release

.github/dependabot.yml
Create `dependabot.yml` in order to have it open automatically PRs for version updates.
Followed the guide [here](https://medium.com/@vladyslav.hontar/dependabot-in-action-d9b56b2be86c).
I think we cannot test it, we need it merged to main and see how it goes.
=> FE-451 Create dependabot.yml

.github/workflows/on-qa-firebase-distribution.yml
The initialization of API URL based on the environment was wrong.
Replace:
`environment: ${{ github.event.inputs.buildType }}`
with:
`environment: ${{ github.event.inputs.environment }}`
=> Fix API url for the specific environment on QA Release workflow

app/src/local/assets/mock_files/get_device_reward_boost.json, app/src/main/java/com/weatherxm/data/ApiModels.kt, app/src/main/java/com/weatherxm/data/datasource/RewardsDataSource.kt, app/src/main/java/com/weatherxm/data/network/ApiService.kt, app/src/main/java/com/weatherxm/data/repository/RewardsRepository.kt
The new API models needed for the new reward boost response.
Created `BoostRewardResponse`, `BoostRewardMetadata` and `BoostRewardDetails` data classes and respective getter functions.
Ensure that the models match the spec's one.
=> FE-665 Get boost rewards data models

app/src/main/res/layout/view_profile_item_card.xml
Fix content padding in Profile item's view.
Replace `contentPaddingEnd` with `contentPaddingRight`.
=> FE-708 Fix content padding in Profile item's view.

app/src/main/AndroidManifest.xml, app/src/main/java/com/weatherxm/data/Failure.kt, app/src/main/java/com/weatherxm/ui/Navigator.kt, app/src/main/java/com/weatherxm/ui/cellinfo/CellInfoActivity.kt, app/src/main/java/com/weatherxm/ui/components/BaseMapFragment.kt, app/src/main/java/com/weatherxm/ui/components/EditLocationMapFragment.kt, app/src/main/java/com/weatherxm/ui/explorer/ExplorerMapFragment.kt, app/src/main/java/com/weatherxm/ui/explorer/ExplorerUIModels.kt, app/src/main/java/com/weatherxm/ui/explorer/ExplorerViewModel.kt, app/src/main/java/com/weatherxm/ui/urlrouteractivity/UrlRouterActivity.kt, app/src/main/java/com/weatherxm/ui/urlrouteractivity/UrlRouterViewModel.kt, app/src/main/java/com/weatherxm/usecases/ExplorerUseCase.kt, app/src/main/java/com/weatherxm/usecases/ExplorerUseCaseImpl.kt, app/src/main/res/values/messages.xml
Handle deep linking of `https://explorer.weatherxm.com/cells/*` URLs.
1. Added the respective `data` block in the `UrlRouterActivity` in the `AndroidManifest`.
2. Created `getCellInfo` function in UseCase which gets all cells and returns the one that matches the predefined `index` or a `CellNotFound` failure.
3. Implemented the "search and return a cell" functionality in `UrlRouterViewModel` in order to properly either fetch the cell and pass it to `CellInfoActivity` and open that activity, either return a failure and handle it accordingly.
4. Added a listener on back pressed on `CellInfoActivity` to open the explorer when this activity gets opened through a deep link
5. The "navigate to location" functionality on Explorer wasn't working, so I made the respective fixes on …
=> FE-706 Feature/cells deep link

app/src/main/java/com/weatherxm/ui/devicesettings/FriendlyNameDialogFragment.kt, app/src/main/res/layout/view_edit_name.xml
Fix the UI issue in the title of the edit name dialog.
Remove `builder.setTitle(getString(R.string.edit_name))` and add the dialog in its respective XML Layout file.
Ensure that the title has the correct (white) background and it's **not** rendered as seen [here](https://linear.app/weatherxm/issue/FE-721/fix-edit-name-dialog-ui).
=> FE-721 Add custom dialog name in edit name dialog to fix the UI issue

gradle/libs.versions.toml
Update Gradle to 8.3.1. Contains a fix to [this](https://github.com/WeatherXM/wxm-android/pull/76).
Just ensure the project builds successfully. An Android Studio update might be needed first.
=> Update Gradle to 8.3.1

app/src/main/res/layout/activity_change_frequency_station.xml, app/src/main/res/layout/activity_connect_wallet.xml, app/src/main/res/layout/activity_delete_account.xml, app/src/main/res/layout/activity_device_alerts.xml, app/src/main/res/layout/activity_device_settings.xml, app/src/main/res/layout/activity_history.xml, app/src/main/res/layout/activity_network_stats.xml, app/src/main/res/layout/activity_preferences.xml, app/src/main/res/layout/activity_reward_boost.xml, app/src/main/res/layout/activity_reward_details.xml, app/src/main/res/layout/activity_reward_issues.xml, app/src/main/res/layout/activity_rewards_list.xml, app/src/main/res/layout/fragment_profile.xml
If/when the content scrolls under the Toolbar, the Toolbar changes color, instead of staying as is in certain screens.
Added `app:liftOnScroll="false"` on each AppBar and fixed in some screens the paddings (clipping when scrolling).
Ensure that the toolbar doesn't change color if/when scrolling in the following screens:
- Settings
- Wallet
- Network Stats
- Historical Charts
- Reward Timeline
- Reward Detail
- Reward Issues
- Boost Detail
- Delete Account
- Station Settings
- Change Frequency
- Device Alerts
=> FE-722 Toolbar fix of changing color when scrolling

app/src/main/java/com/weatherxm/ui/components/DailyRewardsCardView.kt, app/src/main/java/com/weatherxm/ui/rewarddetails/RewardDetailsActivity.kt, app/src/main/java/com/weatherxm/ui/rewardissues/RewardIssuesAdapter.kt, app/src/main/res/layout/activity_preferences.xml, app/src/main/res/layout/view_ble_action_flow.xml, app/src/main/res/values-night/colors.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/palette.xml
Error & Warning annotation summaries have a different color from Figma
- Updated `darkPrimary`, `lightWarningTint`, `darkWarningTint`, `lightErrorTint` and `darkErrorTint` colors.
- Created a new color `infoStrokeColor` to use it in info-related cards as a stroke.
Ensure that the colors are correct and nothing has broken up readability-wise in those cards or other info/warning/error cards in-app.
=> FE-717 Update some colors

app/src/main/java/com/weatherxm/ui/common/Views.kt, app/src/main/java/com/weatherxm/ui/rewardboosts/RewardBoostActivity.kt, app/src/main/java/com/weatherxm/ui/rewarddetails/RewardBoostAdapter.kt, app/src/main/java/com/weatherxm/util/Charts.kt, app/src/main/res/layout/view_daily_rewards_card.xml, app/src/main/res/values/palette.xml
In the loading state of the boost details screen or when the boost type is not supported then we would use the #2780FF as the default color.
Renamed the #2780FF color to `blue` and used it accordingly.
Test a station that has beta rewards boost or any other unknown type and ensure that blue color is shown correctly.
=> FE-734 Fix background color of boost card when loading/unknown

.github/workflows/build-codeanalysis.yml, .github/workflows/on-main-firebase-distribution.yml, .github/workflows/on-qa-firebase-distribution.yml, .github/workflows/production-firebase-distribution.yml
Add a dev URL for the claim app to dev builds.
Changed the GitHub workflows to use the environment secret for `CLAIM_APP_URL` and set those secrets in this repo.
Not testable until merged.
=> FE-750 Use CLAIM_APP_URL from environment secret

app/src/main/java/com/weatherxm/ui/components/RewardsQualityCardView.kt, app/src/main/java/com/weatherxm/ui/rewarddetails/RewardDetailsActivity.kt
Hide base reward icon when QoD is not available.
Created funcion `hideIcon` in `RewardsQualityCardView` which hides the icon in that card and adds the respective left padding to the message in order to start from the same position as the title.
Choose Rural Iris Water station go to the first entry without QOD in timeline (earlier than March 12)
=> FE-761 Hide base reward icon when QoD is not available

app/src/main/java/com/weatherxm/data/ApiModels.kt, app/src/main/java/com/weatherxm/data/repository/RewardsRepository.kt, app/src/main/java/com/weatherxm/ui/common/UIModels.kt, app/src/main/java/com/weatherxm/ui/rewardslist/RewardsListActivity.kt, app/src/main/java/com/weatherxm/ui/rewardslist/RewardsListAdapter.kt, app/src/main/java/com/weatherxm/ui/rewardslist/RewardsListViewModel.kt, app/src/main/java/com/weatherxm/usecases/RewardsUseCase.kt, app/src/main/res/layout/activity_rewards_list.xml, app/src/main/res/layout/list_item_reward.xml, app/src/main/res/layout/list_item_reward_end_of_data.xml, app/src/main/res/values/messages.xml, app/src/main/res/values/strings.xml
Limit timeline data to 3 months in the past. Some UI fixes and added an end of data card.
- Create a new object TimelineReward for a better approach based on Pantelis comment below. 
- When we get to the end of the data, we add a new `TimelineReward` with `type = END_OF_DATA` at the end of the list which the adapter handles to show the respective "end of data card" at the end of the list.
- Removed the functionality of `timezone`, `fromDate`, `toDate` in the API call in the ViewModel and UseCase as these are not needed anymore and it's part of the `Repository` to create the proper `fromDate` for the DataSource etc.
Check any station's reward timeline and ensure everything is OK and you can see the "End of data" card at the 3-months mark.
=> FE-754 Limit Reward Timeline data

app/src/main/java/com/weatherxm/ui/Navigator.kt, app/src/main/java/com/weatherxm/ui/devicealerts/DeviceAlertsActivity.kt, app/src/main/java/com/weatherxm/ui/devicedetails/DeviceDetailsActivity.kt, app/src/main/java/com/weatherxm/ui/devicedetails/current/CurrentFragment.kt, app/src/main/java/com/weatherxm/ui/home/devices/DevicesFragment.kt, app/src/main/java/com/weatherxm/usecases/DeviceDetailsUseCaseImpl.kt, app/src/main/java/com/weatherxm/util/Analytics.kt, app/src/main/res/layout/activity_device_details.xml, app/src/main/res/layout/fragment_device_details_current.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Integrate low battery warning in station details.
- Introduce the new `Chip` in the layout file, along with `ChipGroup` and `HorizontalScrollView`.
- Created a new function in `DeviceDetailsActivity` named `setAlerts` which handles the text/visibility of this "alert" `Chip`
- Removed the overflow cards below the weather card except the `offline` one where we will keep the same logic.
- When the device is offline make the status chip clickable, upon click the app navigates to the Alert screen.
- Add the respective code in `DeviceDetailsUseCaseImpl` to return the "Low Battery" alert (currently will return it **in all** owned devices as the testing code is there but marked with a `#FIXME` comment)
Ensure that all 3 different type of alerts are shown correctly in the station details screen …
=> FE-753 Feature/low battery station details

app/src/main/java/com/weatherxm/ui/rewardsclaim/RewardsClaimActivity.kt, app/src/main/res/layout/activity_webview.xml
Push the layout up when keyboard is shown on webview activity
1. Removed the `android:fitsSystemWindows="false"` from the webview XML file.
Added `binding.root.setFitsSystemWindows(true)` in the Rewards Claiming activity.
Try a claim and ensure the layout gets pushed up when keyboard is shown when clicking the "amount" section.
=> FE-794 Push the layout up when keyboard is shown on webview activity

app/src/main/java/com/weatherxm/ui/home/devices/DevicesAdapter.kt
When there are >1 devices with alerts and others with no alerts, clear the stroke due to unexpected results on refreshing (e.g. stroke showing on devices with no alerts).
`binding.root.strokeWidth = 0` when there are no alerts.
Have in your devices list stations with alerts and no alerts, swipe down to refresh and ensure that the stroke is not visible in your "OK" stations.
=> FE-803 Fix unexpected stroke on devices list

app/src/main/java/com/weatherxm/ui/components/DailyRewardsCardView.kt
Fix reward issues message showing "minor" when there is an error
Sort the severities before checking against them if the most important one is an info (minor) or an error/warning (non-minor).
Test against various stations that have issues that the correct message is shown in the rewards tab and in the timeline (e.g. minor vs non-minor etc)
=> FE-800 Fix reward issues message showing "minor" when there is an error

app/build.gradle.kts
Fix getting latest tag through `grgit`
Sort the tags by `dateTime`
=> FE-843 Fix getting latest tag

app/src/main/java/com/weatherxm/ui/common/Views.kt, app/src/main/java/com/weatherxm/ui/deviceforecast/DailyTileForecastAdapter.kt, app/src/main/java/com/weatherxm/ui/deviceforecast/ForecastDetailsActivity.kt, app/src/main/java/com/weatherxm/usecases/ChartsUseCaseImpl.kt
1. Fixed a crash in historical screen when using bf as a wind unit.
2. Optimized auto-scrolling on selection in daily tiles in forecast details
- Fixed the crash by proper handling the conversion of wind gust values, the same way as we handle already the wind speed values.
- Created extension function `moveItemToCenter` which auto-scrolls the item to the center of the screen on a `RecyclerView`.
1. Use `bf` as a wind unit and ensure everything is OK in the historical charts.
2. Scroll and select through daily tiles in forecast details
=> FE-845 FE-844 Feature/internal release fixes

app/src/main/java/com/weatherxm/data/bluetooth/BluetoothConnectionManager.kt
Catch the `NotConnectedException` in order to avoid crashes.
Edge case, I'm not sure if there is a point in testing it or how to.
=> FE-850 Catch a rare NotConnectedException when disconnecting bluetooth

app/src/main/java/com/weatherxm/ui/Navigator.kt, app/src/main/java/com/weatherxm/ui/claimdevice/helium/result/ClaimHeliumResultFragment.kt, app/src/main/java/com/weatherxm/ui/claimdevice/location/ClaimLocationFragment.kt, app/src/main/java/com/weatherxm/ui/claimdevice/selectstation/SelectStationTypeActivity.kt, app/src/main/java/com/weatherxm/ui/claimdevice/wifi/result/ClaimWifiResultFragment.kt, app/src/main/res/layout/activity_claim_wifi_device.xml, app/src/main/res/layout/fragment_claim_set_location.xml, app/src/main/res/layout/fragment_claim_wifi_connect_wifi.xml, app/src/main/res/layout/fragment_claim_wifi_manual_details.xml, app/src/main/res/layout/fragment_claim_wifi_prepare_claiming.xml, app/src/main/res/layout/fragment_claim_wifi_result.xml, app/src/main/res/layout/view_marker.xml, app/src/main/res/values/strings.xml
Claim Wizard step 4: Confirm station Location.
Created a different M5/D1 container in the same layout as the current "set location" screen and toggle visibility & handling in the Fragment depending on which `DeviceType` we have.
This is a **temp & simple workaround** until the design team updates the Helium screens as well, which is already WIP.
Ensure that the M5/D1 step matches the design and the Helium's respective step is OK as well. Also try some claiming tests in M5 and D1 and ensure everything is OK.
=> FE-827 Feature/refactor claim set location

app/src/main/java/com/weatherxm/ui/rewardsclaim/RewardsClaimViewModel.kt
Add the param via the `getQueryParams` function in `RewardsClaimViewModel`
You can put a breakpoint after building the query params and ensure that the `embed=true` is there.
=> FE-906 Add embed=true as a query param when opening the claim DApp

app/src/main/java/com/weatherxm/ui/claimdevice/wifi/manualdetails/ClaimWifiManualDetailsFragment.kt
Fix validation of serial number & claiming key inputs as it allows to proceed with an invalid serial number by using the "Enter" key on the keyboard.
Refactor how we validate the input fields as before we didn't "terminate" the execution of the `fun` when an error was found.
Ensure that it's not possible to proceed either with the button or with the enter in the keyboard when the serial number and/or the claiming key are invalid. Also check M5's manual input.
=> FE-911 Fix validation of serial number & claiming key inputs

app/src/main/java/com/weatherxm/data/ApiModels.kt
Add `D1` and `Pulse` in `enum class DeviceProfile`.
=> FE-919 Add D1 and Pulse in device profiles

app/src/main/java/com/weatherxm/ui/home/profile/ProfileFragment.kt, app/src/main/res/layout/fragment_profile.xml, app/src/main/res/values/strings.xml
Add helpful indication in allocated rewards that desktop claiming is available as well
Reuse the same `MessageCardView` we had for the "Buy Station" prompt for this case as well. And set the stroke/title/messages accordingly on each case.
Ensure that both cases (Buy Station and Claim via Web) are visible correctly.
=> FE-901 Indication in allocated rewards

app/src/main/assets/countries_information.json, app/src/main/java/com/weatherxm/data/DataModels.kt, app/src/main/java/com/weatherxm/data/FrequencyHelper.kt
- Added the respective entry in `enum class Frequency` and in the `frequencyToHeliumBleBandValue` mapping function.
- Map Malaysia to `AS923_1B`.
The `AS923_1B` should be available in the frequencies list in the Change Frequency screen.
=> FE-936 Add support for AS923_1B and map it to Malaysia

app/src/main/java/com/weatherxm/data/repository/DeviceOTARepository.kt, app/src/main/java/com/weatherxm/ui/claimdevice/helium/result/ClaimHeliumResultFragment.kt, app/src/main/java/com/weatherxm/ui/common/UIModels.kt, app/src/main/java/com/weatherxm/ui/devicedetails/DeviceDetailsViewModel.kt, app/src/main/java/com/weatherxm/ui/devicesettings/DeviceSettingsViewModel.kt, app/src/main/java/com/weatherxm/ui/home/devices/DevicesAdapter.kt, app/src/main/java/com/weatherxm/usecases/DeviceDetailsUseCaseImpl.kt, app/src/main/java/com/weatherxm/usecases/DeviceListUseCaseImpl.kt, app/src/main/java/com/weatherxm/usecases/StationSettingsUseCase.kt, app/src/main/java/com/weatherxm/usecases/StationSettingsUseCaseImpl.kt
🍝 code. 😢 
- Better name of `shouldShowOTAPrompt` function, renamed to `userShouldNotifiedOfOTA` which better shows what this function does
- Created an extension function in `UIDevice` called `shouldPromptUpdate` which make all the checks needed in case we should prompt the user for an update or not
- Created an extension function in `UIDevice` called `createDeviceAlerts` which creates a list of `DeviceAlert` alerts so that UseCases call this function and not have duplicate code
Ensure that OTA prompts are shown correctly when/if needed (you can try with mock version also).
=> FE-934 Some code optimizations regarding DeviceAlerts and shouldShowOTAPrompt check

app/src/local/assets/mock_files/get_device_rewards_timeline.json, app/src/main/java/com/weatherxm/ui/cellinfo/CellInfoActivity.kt, app/src/main/java/com/weatherxm/ui/components/DailyRewardsCardView.kt, app/src/main/java/com/weatherxm/ui/rewarddetails/RewardDetailsActivity.kt, app/src/main/res/values/plurals.xml, app/src/main/res/values/strings.xml
Use Plurals and get them as quantity strings where applicable.
- Created a `plurals.xml` values file where we setup our new quantity strings
- Removed the now deprecated strings from `strings.xml`
- Use `getQuantityString` function as described [here](https://stackoverflow.com/questions/41950952/how-to-use-android-quantity-strings-plurals](https://stackoverflow.com/questions/41950952/how-to-use-android-quantity-strings-plurals) in order to get the correct string which eventually reduces the number of `if...else` checks and simplifies the code.
1. Ensure that the following screens work correctly for 0, 1 and more than 1 alerts/issues. Try either against the API or by playing with local mock.
- Rewards Timeline - `get_device_rewards_timeline.json`
- Reward Details - …
=> FE-948 Use Plurals and get them as quantity strings where applicable

app/src/main/java/com/weatherxm/ui/devicesettings/FriendlyNameDialogFragment.kt, app/src/main/java/com/weatherxm/util/Validator.kt, app/src/main/res/layout/view_edit_name.xml
Correct validation of friendly name.
Match when the following are met:
- any char
- min length = 1
- max length = 24
- non empty text (i.e. `return false` when only white space characters are used), new Regex `^\\S.{1,24}$`
Added the below code in order to remove the error shown when the user is typing and disable the "Save" button when the input is empty.
```
binding.newName.onTextChanged {
binding.newNameContainer.error = null
binding.save.isEnabled = it.isNotEmpty()
}
```
Ensure that strings longer than >24 chars are not validating correctly and that only non-empty strings are matched.
=> FE-984 Validation of friendly name

app/src/main/java/com/weatherxm/ui/home/HomeActivity.kt
Issue with a screen recording can be found [here](https://linear.app/weatherxm/issue/FE-961/add-button-is-not-visible).
Don't use the `visible` function in any case for the `addButton` and better handling of the previous caught bug.
Watch the video [here](https://linear.app/weatherxm/issue/FE-961/add-button-is-not-visible) and ensure that this behavior is not taking place anymore.
=> FE-961 Fix add button not visible

app/src/main/java/com/weatherxm/ui/claimdevice/location/ClaimLocationFragment.kt, app/src/main/java/com/weatherxm/ui/claimdevice/pulse/ClaimPulseActivity.kt
Add Location in the Claiming Flow
Added `ClaimLocationFragment` in the flow with `DeviceType.PULSE_4G` in order to handle the `next` button in that screen with the Pulse-related `ViewModel`
Ensure that everything looks OK in the flow at the location part.
=> FE-928 Integrate Claiming Pulse Step 4 - Location

app/src/main/java/com/weatherxm/util/Validator.kt
Fix Regex of Friendly Name allowing 1 char
Replaced the regex with the correct one.
Ensure that name is between 1 and 24 chars (not less, not more).
=> Fix Regex of Friendly Name allowing 1 char

app/build.gradle.kts, app/src/main/java/com/weatherxm/data/Modules.kt, app/src/main/java/com/weatherxm/ui/preferences/PreferenceFragment.kt, app/src/main/java/com/weatherxm/ui/preferences/PreferenceViewModel.kt, app/src/main/java/com/weatherxm/usecases/PreferencesUseCase.kt, app/src/main/res/xml/preferences.xml
Add installationId as a suffix in App Version in settings
Get `installationId` through Repo -> UseCase -> ViewModel -> Fragment and then append it at the currently shown "app version".
```
/**
* If `installationId` is available, append it at the end of the app version
*/
model.getInstallationId()?.let {
appVersionPref?.summary = getString(R.string.app_version) + "-$it"
}
```
Ensure that the installationId is there.
=> FE-993 Add installationId as a suffix in App Version in settings

app/src/main/java/com/weatherxm/data/bluetooth/BluetoothConnectionManager.kt, app/src/main/java/com/weatherxm/ui/widgets/currentweather/CurrentWeatherWidgetWorkerUpdate.kt
Better non-fatal reporting in some cases as we do not need some reports we had (e.g. user cancelled reported as non-fatal error).
- Replaced in 2 instances `Timber.w` with `Timber.d` in order not to record it on Crashlytics and left a respective comment
- In Widget Updater Worker record on Crashlytics only the failures associated with `Result.retry` which are the unexpected ones we need to find their cause and solve them.
=> FE-1016 Better non-fatal reporting in some cases.

app/src/main/java/com/weatherxm/ui/deviceforecast/ForecastDetailsActivity.kt, app/src/main/java/com/weatherxm/ui/deviceforecast/ForecastDetailsViewModel.kt
Prevent a crash and print some logs in FirebaseCrashlytics so we can figure out the cases it happens in Forecast Details.
If `position == -1` (which produces a crash afterwards), catch it, return `0` as the fallback and print the error through `Timber.e` so we can try to reproduce it afterwards.
Not testable as I haven't reproduced it yet. So I'm printing some logs in Firebase Crashlytics in case they help.
=> FE-1013 Prevent a crash and print some logs in FirebaseCrashlytics

app/src/main/java/com/weatherxm/ui/home/profile/ProfileFragment.kt
Replaced `STATUS` with `STATE`.
=> FE-1022 Use STATE instead of STATUS in token claiming result event

app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt, app/src/main/java/com/weatherxm/analytics/AnalyticsWrapper.kt, app/src/main/java/com/weatherxm/app/AnalyticsInitializer.kt, app/src/main/java/com/weatherxm/data/services/CacheService.kt, app/src/test/java/com/weatherxm/analytics/AnalyticsWrapperTest.kt
Add in Analytics User Properties the `STATIONS_OWN` and `HAS_WALLET` params.
Save the respective entries in `SharedPreferences` and use them on `AnalyticsInitializer` in order to set them as user params.
Ensure that these params are logged correctly **after** the first run (as the cache needs to be initialized first) by checking the logger in Android Studio.
=> FE-1029 Feature/user properties owned stations wallet

app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt
Forecast Tab and Forecast Details screen names were wrong.
1. Device Forecast Tab ---> Device Forecast
2. Forecast Details Screen ---> Device Forecast Details
Ensure that the new names are according our analytics spec.
=> FE-1064 Fix forecast screen names

.github/workflows/on-main-firebase-distribution.yml, .github/workflows/on-pr.yml, .github/workflows/on-qa-firebase-distribution.yml, .github/workflows/production-distribution.yml, app/build.gradle.kts
Use Flavor-specific `MIXPANEL_TOKEN` in order to integrate the new `DEV` token for the Mixpanel.
1. In `app/build.gradle` get the `MIXPANEL_TOKEN` through `getFlavorProperty` which takes the property from the flavor-specific `.env` and if it doesn't exist it uses the default one.
2. Use the `environment` variables in GitHub workflows to get the `MIXPANEL_TOKEN`
3. Updated those environment variables in this repo.
Ensure that events are logged in the dev project when running a dev flavor.
=> FE-1065 Use Flavor-specific MIXPANEL_TOKEN

app/src/main/java/com/weatherxm/util/Rewards.kt, app/src/test/java/com/weatherxm/util/RewardsTest.kt
$WXM should be displayed with two decimals places
In `formatTokens` instead of `val decimalFormat = DecimalFormat("0.00##")` use `val decimalFormat = DecimalFormat("0.00")`
Ensure that all screens affected (as reported in the Linear issue) are OK.
=> FE-1071 Use 2 decimals on tokens

app/proguard-rules.pro
Crashes taking place in 4.1.1.
Add Proguard rules for keeping Either due to using it in the network response adapter.
=> FE-1097 Fix crashes in 4.1.1

app/src/main/AndroidManifest.xml, app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt, app/src/main/java/com/weatherxm/data/Modules.kt, app/src/main/java/com/weatherxm/data/datasource/UserPreferenceDataSource.kt, app/src/main/java/com/weatherxm/data/repository/UserPreferencesRepository.kt, app/src/main/java/com/weatherxm/data/services/CacheService.kt, app/src/main/java/com/weatherxm/ui/Navigator.kt, app/src/main/java/com/weatherxm/ui/common/Contracts.kt, app/src/main/java/com/weatherxm/ui/deleteaccount/DeleteAccountActivity.kt, app/src/main/java/com/weatherxm/ui/deleteaccountsurvey/DeleteAccountSurveyActivity.kt, app/src/main/java/com/weatherxm/ui/deleteaccountsurvey/DeleteAccountSurveyViewModel.kt, app/src/main/java/com/weatherxm/ui/preferences/PreferenceActivity.kt, app/src/main/java/com/weatherxm/ui/preferences/PreferenceFragment.kt, app/src/main/java/com/weatherxm/ui/preferences/PreferenceViewModel.kt, app/src/main/java/com/weatherxm/usecases/DeleteAccountSurveyUseCase.kt, app/src/main/java/com/weatherxm/usecases/PreferencesUseCase.kt, app/src/main/res/layout/activity_preferences.xml, app/src/main/res/values/company_info.xml, app/src/main/res/values/preferences.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, app/src/test/java/com/weatherxm/data/repository/UserPreferencesRepositoryTest.kt
Remove "Short App survey" option in Preferences & Settings screen
- Removed all relevant entries from the station settings, the data sources, the repositories and the cache
- Renamed `SendFeedbackXXX` to `DeleteAccountSurveyXXX` as this is the only use-case it currently serves as an in-app webview with JS Injection
Ensure that the option is not visible anymore in settings.
=> FE-1081 Remove app survey prompt from the settings

app/src/main/java/com/weatherxm/data/Modules.kt, app/src/main/java/com/weatherxm/ui/explorer/ExplorerActivity.kt, app/src/main/java/com/weatherxm/ui/explorer/ExplorerMapFragment.kt, app/src/main/java/com/weatherxm/ui/explorer/ExplorerUIModels.kt, app/src/main/java/com/weatherxm/ui/explorer/ExplorerViewModel.kt, app/src/main/java/com/weatherxm/ui/home/HomeActivity.kt, app/src/main/java/com/weatherxm/usecases/ExplorerUseCase.kt, app/src/main/java/com/weatherxm/usecases/ExplorerUseCaseImpl.kt, app/src/main/java/com/weatherxm/util/MapboxUtils.kt, app/src/test/java/com/weatherxm/util/MapboxUtilsTest.kt
Fix map blinking by checking if new cells have been added in the explorer and using new onStatus, onExplorerData, onNewPolygons in order to populate the UI.
- Moved some functions in MapboxUtils where they should have been located
- Instead of using `explorerState` for everything (holding the data, showing the status of the network call, updating the UI), we created 3 different `LiveData`:
- `onExplorerData` which is responsible for holding the data of the explorer
- `onStatus`  which is responsible for representing the status of the network call (success/loading/error)
-  `onNewPolygons` which is responsible for sending an event to the UI to draw the new Polygons (after the first fetch)
- Afterwards on `fetch` we handle everything accordingly and use the event we need in each case. We …
=> FE-1104 Fix map blinking

app/src/main/java/com/weatherxm/util/Charts.kt
Solar irradiance "trend line" never gets to 0 on X axis.
Moved the `axisRight.axisMinimum = 0F` to the correct place (after `setDefaultSettings(...)`).
Ensure that solar radiation line gets to 0.
=> FE-1135 Fix solar chart axis minimum

app/src/main/java/com/weatherxm/ui/claimdevice/pulse/ClaimPulseActivity.kt, app/src/main/java/com/weatherxm/ui/components/RangeSelectorView.kt, app/src/main/java/com/weatherxm/ui/devicesrewards/DeviceRewardsAdapter.kt, app/src/main/res/layout/list_item_device_rewards.xml, app/src/main/res/layout/view_range_selector.xml
Two crashes (one reported internally, one reported in Firebase which was fixed in the past and broken again).
Disallow unchecking range selector in charts and use a default empty string instead of null in claiming of pulse in a rare case)
Ensure that double tapping in the same chip in the chart range selector in Rewards Analytics does not cause a crash or an uncheck.
=> FE-1144 FE-1142 Fixing of 2 crashes

.github/workflows/on-main-firebase-distribution.yml, README.md
When pushing on main branch, run the task for getting a report for unit test coverage and deploy it in GitHub pages
- Added a new `deploy_coverage` job in the _on-main-push_ workflow.
- Updated README to contain code coverage information
Can't be tested, need to get it merged and then pray 🙏 
Lots of testing has been done in #320
=> FE-1145 Upload Coverage HTML Report by using a custom action

.github/workflows/on-main-firebase-distribution.yml
Failed action: https://github.com/WeatherXM/wxm-android/actions/runs/10941798207/job/30377271777
Add Permissions to the job in order to be able to deploy on GitHub Pages
=> Add Permissions to the job in order to be able to deploy on GitHub Pages

.github/workflows/on-main-firebase-distribution.yml, app/build.gradle.kts
Fix directory location of code coverage tool
Use `reports/jacoco/coverage-report` as the directory which the code coverage report is stored and served afterward.s
=> [Hotfix] Fix directory location of code coverage tool

app/src/main/java/com/weatherxm/usecases/RewardsUseCase.kt, app/src/test/java/com/weatherxm/TestConfig.kt, app/src/test/java/com/weatherxm/TestUtils.kt, app/src/test/java/com/weatherxm/data/ExtensionsTest.kt, app/src/test/java/com/weatherxm/usecases/ChartsUseCaseTest.kt, app/src/test/java/com/weatherxm/usecases/RewardsUseCaseTest.kt, app/src/test/java/com/weatherxm/usecases/StatsUseCaseTest.kt, app/src/test/java/com/weatherxm/util/DateTimeHelperTest.kt
Some missing unit tests for `RewardsUseCase` and for `Data.Extensions`
- Created the 2 last unit tests missing from `RewardsUseCase`. 
- Created functions `getTooltipDate` and `getXAxisLabel` as we had the same code in 2 different places.
- Created unit tests for `Data.Extensions` file.
Just make sure the action below that runs unit tests completes with 100% success.
=> FE-1143 RewardsUseCase & Data.Extensions unit tests

app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt, app/src/main/java/com/weatherxm/ui/devicedetails/forecast/DailyForecastAdapter.kt, app/src/main/java/com/weatherxm/ui/devicedetails/forecast/ForecastFragment.kt
We have two analytics events on Daily Card click in Forecast Tab. So this PR fixes it.
Keep the old one: `(.selectContent, parameters: [.contentType: .dailyCard, .itemId: .dailyForecast])` and add the `index` param.
Ensure that the proper event is logged.
=> FE-1169 Fixed analytics event on daily card click in forecast

app/src/local/assets/mock_files/get_user_device.json, app/src/main/java/com/weatherxm/ui/components/MessageCardView.kt, app/src/main/java/com/weatherxm/ui/devicealerts/DeviceAlertsActivity.kt, app/src/main/java/com/weatherxm/ui/devicealerts/DeviceAlertsAdapter.kt, app/src/main/res/layout/activity_device_alerts.xml
Alerts screen design changes
Updated alerts screen's top bar and used the new icons in low battery and update required alerts.
If you don't have such a station, play with local mock in order to create a station consisting of low battery, update required and inactive alerts and view its Alerts screen.
=> FE-1198 Alerts screen design changes

app/src/main/java/com/weatherxm/ui/common/Contracts.kt, app/src/main/java/com/weatherxm/ui/home/profile/ProfileFragment.kt
Use the error state with `N/A` when we encounter an API error in the rewards in the profile screen.
Show the `N/A` values respectively.
Reproduce it with an error (e.g. turn internet off and go to profile screen) and ensure everything looks according to the spec.
=> FE-1263 My profile: Total earned & Total claimed tokens error state

app/src/main/java/com/weatherxm/ui/devicesettings/BaseDeviceSettingsViewModel.kt, app/src/main/java/com/weatherxm/ui/devicesettings/UIModels.kt
There is a bug currently with the content copied when clicking the "Share" button to not follow the spec we have agreed onto.
1. Created a function `toFormattedString` in `DeviceInfoItem` UI Model and
2. Fixed the function `parseDeviceInfoToShare` in `BaseDeviceSettingsViewModel` by using the above function.
Just ensure that the text to share is correct (content-wise and format-wise) as it should be in the same format as the iOS does.
=> FE-1299 Fix the content to share in the station settings screen

app/src/main/res/values/strings.xml
Update message when an owned station has an inactive alert
Used the new message:
> The station is not sending weather data. Check your network connection and the outdoor unit’s batteries. If the problem persists, contact our support team.
Just ensure the new message on an inactive owned station is correct.
=> FE-1309 Update message when an owned station has an inactive alert

app/build.gradle.kts, app/src/main/java/com/weatherxm/ui/claimdevice/helium/pair/ClaimHeliumPairViewModel.kt, app/src/main/java/com/weatherxm/ui/components/BluetoothHeliumViewModel.kt, app/src/main/java/com/weatherxm/ui/deviceheliumota/DeviceHeliumOTAViewModel.kt, app/src/main/java/com/weatherxm/util/CountDownTimerHelper.kt, app/src/test/java/com/weatherxm/TestConfig.kt, app/src/test/java/com/weatherxm/ui/claimdevice/helium/pair/ClaimHeliumPairViewModelTest.kt, app/src/test/java/com/weatherxm/ui/devicesettings/helium/changefrequency/ChangeFrequencyViewModelTest.kt, app/src/test/java/com/weatherxm/ui/devicesettings/helium/reboot/RebootViewModelTest.kt
Create a Count Down helper class to encapsulate `CountDownTimer` in order to reuse this class and be able to unit test the functionality as `CountDownTimer` is an Android library.
- Created a `CountDownTimerHelper` class to encapsulate the `CountDownTimer` functionality and use this class in `BluetoothHeliumViewModel` and `ClaimHeliumPairViewModel`.
- Fixed the unit tests that were missing due to having this Android class directly in our ViewModels.
1. Ensure that the timer works correctly (can be checked in BLE scanning in the Helium's claiming flow as the `CountDownTimer` is used to show the progress which is shown in the "Scan Again" button)
2. Just make sure the tests run successfully (can be checked through the GitHub Action below as well).
=> FE-1306 CountDownTimer helper class

app/src/main/java/com/weatherxm/ui/devicedetails/DeviceDetailsActivity.kt, app/src/main/java/com/weatherxm/ui/devicedetails/forecast/ForecastFragment.kt, app/src/main/res/layout/activity_device_details.xml, app/src/main/res/layout/list_item_device.xml
…recast when unfollowed, remove click action on status chip when offline
Some fixes after product testing in Network Health.
1. Removed the info button of forecast when "Hidden Content" is displayed on unfollowed stations
2. Devices List --> No Data --> Added bottom padding
3. Removed the click action from the status chip showing the last active time when it's offline
Ensure that the 3 issues mentioned are fixed.
=> FE-1318 Network Health fixes

app/src/main/java/com/weatherxm/ui/devicedetails/forecast/ForecastFragment.kt
Update forecast's tab device model on device polling updates
```
parentModel.onDevicePolling().observe(viewLifecycleOwner) {
model.device = it
}
```
1. Open Device Details -> Forecast
2. Open Station Settings
3. Use a new friendly name
4. Go back
5. Open a daily forecast screen
6. Ensure the new friendly name shows up
=> FE-1319 Friendly name, does not change in forecast 

app/src/main/java/com/weatherxm/ui/common/DevicesAdapter.kt, app/src/main/java/com/weatherxm/ui/common/Views.kt, app/src/main/java/com/weatherxm/ui/components/WeatherCardView.kt, app/src/main/java/com/weatherxm/ui/devicealerts/DeviceAlertsAdapter.kt, app/src/main/java/com/weatherxm/ui/devicedetails/current/CurrentFragment.kt, app/src/main/java/com/weatherxm/ui/widgets/RemoteViews.kt, app/src/main/java/com/weatherxm/ui/widgets/selectstation/SelectStationAdapter.kt, app/src/main/res/values/strings.xml
Update No Data message for public (non-owned) device
1. Updated the `no_data_message_public_device` to the new text
2. Created a new `station_inactive_alert_message_public` for the alerts screen as we reused the above one before.
Ensure both texts look correct on non-owned stations.
=> FE-1323 Update No Data message for public (non-owned) device

app/src/main/java/com/weatherxm/util/Charts.kt
When there is a significant change in a chart's metric, the curved lines can create a strange visual effect in the charts that may distort the data representation. The recommended solution here is to replace the curved lines with straight ones in all our data graphs (forecast and historical)
Replaced `CUBIC_BEZIER` with `LINEAR`.
Ensure that everything looks OK in Historical & Forecast charts.
=> FE-1312 Use Linear lines in historical and forecast charts

app/src/main/java/com/weatherxm/ui/common/HourlyForecastAdapter.kt
Show minutes in 12-hour format in hourly forecast
Removed the `showMinutesIn12HourFormat=false` argument
Just make sure everything looks OK.
=> Show minutes in 12-hour format in hourly forecast

app/build.gradle.kts, app/src/main/java/com/weatherxm/data/ClientIdentificationHelper.kt, app/src/main/java/com/weatherxm/service/MessagingService.kt
For upgrading our code and not having to support really old devices.
- Updated `minSdk` to 28 ([Android 9](https://apilevels.com/))
- Removed some deprecated now `if` checks
Ensure that the projects builds successfully and everything looks OK.
=> Increase `minSdk` to 28 (Android 9)

app/src/main/AndroidManifest.xml, app/src/main/java/com/weatherxm/ui/Navigator.kt, app/src/main/java/com/weatherxm/ui/common/Contracts.kt, app/src/main/java/com/weatherxm/ui/photoverification/gallery/PhotoGalleryActivity.kt, app/src/main/java/com/weatherxm/ui/photoverification/gallery/PhotoGalleryViewModel.kt
After capturing a photo and pressing the upload button, the user should have the option to share their photos by selecting the corresponding button.
- Created function `openShareImages` which is responsible for sharing the images, given an `ArrayList<Uri>`.
Follow the flow in **local mock** and in the gallery I have transformed the **Upload** button to be used as "Share".
=> Share photos implementation (including test code)

app/src/main/java/com/weatherxm/ui/rewarddetails/RewardDetailsActivity.kt
Use the correct ranges for the QoD scores in order for the QoD card to being shown up as success/warning/error
Replaced the wrong ranges with the correct ones.
Ensure that the new ranges work correctly in the UI. You can also play with local mock to use any number you want, in the JSON `get_device_reward_details.json`
=> Fix QoD color outline on Reward Details

app/src/main/java/com/weatherxm/usecases/ExplorerUseCaseImpl.kt
Create alerts on cell devices
Run `createDeviceAlerts` at the respective place in the UseCase when populating each `UIDevice` of the list.
Go to a cell with an offline station and ensure that the "Inactive" chip is shown in this cell screen.
=> Fixed no alerts in cell devices

app/src/main/java/com/weatherxm/data/Modules.kt, app/src/main/java/com/weatherxm/data/datasource/DevicePhotoDataSource.kt, app/src/main/java/com/weatherxm/data/repository/DevicePhotoRepository.kt, app/src/main/java/com/weatherxm/data/services/CacheService.kt, app/src/main/java/com/weatherxm/ui/devicesettings/helium/DeviceSettingsHeliumActivity.kt, app/src/main/java/com/weatherxm/ui/devicesettings/wifi/DeviceSettingsWifiActivity.kt, app/src/main/java/com/weatherxm/ui/photoverification/intro/PhotoVerificationIntroActivity.kt, app/src/main/java/com/weatherxm/ui/photoverification/intro/PhotoVerificationIntroViewModel.kt, app/src/main/java/com/weatherxm/usecases/DevicePhotoUseCase.kt, app/src/test/java/com/weatherxm/data/services/PrefsSingleVarTest.kt
Do not show the intro screen of the photo verification if the user has already accepted the terms once
1. Used `CacheService` to set/get a `boolean` indicating if the user has accepted the terms or not.
2. Pass this data through data source, repo and use case.
3. In `PhotoVerificationIntroActivity` if the user has already accepted the terms, `finish()` it and open `PhotoGalleryActivity`. Created `PhotoVerificationViewModel` to get that data.
4. In Station Settings if the gallery is empty, the intro screen show open and not the gallery directly.
Use local mock flavour. Navigate to the photo verification flow from claiming flow or through the settings and ensure that after accepting the terms once and move past the intro screen, it doesn't show up again in the next attempt.
=> [Photo Verification] Do not display the terms screen if the user has already accepted it.

app/src/main/java/com/weatherxm/data/models/ApiModels.kt, app/src/main/java/com/weatherxm/ui/common/RewardSplitStakeholderAdapter.kt, app/src/main/res/layout/list_item_reward_split_stakeholder.xml, app/src/test/java/com/weatherxm/ui/devicesettings/helium/DeviceSettingsHeliumViewModelTest.kt, app/src/test/java/com/weatherxm/ui/devicesettings/wifi/DeviceSettingsWifiViewModelTest.kt, app/src/test/java/com/weatherxm/ui/rewarddetails/RewardDetailsViewModelTest.kt
Reward split breaks when receives FLOAT instead of INT
Instead of `Int` we now use `Float` in the `ApiModels` and minor adjustments in the UI to use a bit more space and show 2 decimals.
Ensure everything is OK, test station: Tame Canvas Forecast
=> Add support of Float with 2 decimals for reward split percentages

app/src/main/java/com/weatherxm/data/Modules.kt, app/src/main/java/com/weatherxm/ui/updateprompt/UpdatePromptViewModel.kt, app/src/main/java/com/weatherxm/usecases/UpdatePromptUseCase.kt, app/src/test/java/com/weatherxm/usecases/UpdatePromptUseCaseTest.kt
Currently it's `class UpdatePromptViewModel(private val appConfigRepository: AppConfigRepository)` which breaks our pattern as it should use a usecase.
Created the usecase, inject it in ViewModel and created the respective unit tests.
Ensure project builds successfully and new tests are OK.
=> `UpdatePromptViewModel` should use a `usecase`

app/src/main/java/com/weatherxm/ui/home/HomeActivity.kt, app/src/main/java/com/weatherxm/ui/home/HomeViewModel.kt, app/src/main/java/com/weatherxm/ui/home/devices/DevicesFragment.kt, app/src/main/java/com/weatherxm/ui/home/devices/DevicesViewModel.kt, app/src/main/java/com/weatherxm/ui/home/profile/ProfileFragment.kt, app/src/main/res/layout/fragment_profile.xml, app/src/test/java/com/weatherxm/ui/home/HomeViewModelTest.kt, app/src/test/java/com/weatherxm/ui/home/devices/DevicesViewModelTest.kt
When Info banner is displayed not able to press Preferences and settings.
Scrolling on profile shows/hides the bottom navigation just like we do in devices. Moved the respective functions in `HomeViewModel` instead of the `DevicesViewModel` it was before.
Ensure that everything looks OK. You can retirn in `HomeViewModel` on `getSurvey` a new `Survey` with multiple `\n` (line breaks) in the "message" argument so that this screen captures more than the available height and scrolling will be needed.
=> Fix bug on scrolling & bottom navigation in profile hiding elements

app/src/main/java/com/weatherxm/data/repository/AuthRepositoryImpl.kt, app/src/test/java/com/weatherxm/data/repository/AuthRepositoryTest.kt
When first name and last names are empty, replace them with null in sign up.
```
val first = if (firstName.isNullOrEmpty()) null else firstName
val last = if (lastName.isNullOrEmpty()) null else lastName
```
Make two test sign-ups and make sure everything is OK:
1. With first and last name empty
2. With first and last name filled
=> Android new user registration returns API error when first or last name are empty

app/src/main/java/com/weatherxm/ui/components/LoginPromptDialogFragment.kt, app/src/main/java/com/weatherxm/ui/components/TermsDialogFragment.kt, app/src/main/java/com/weatherxm/ui/devicesettings/FriendlyNameDialogFragment.kt
Fix crashes on dialogs (e.g. Terms dialog).
Auto-dismiss the dialog when it's restored from saved instance (e.g. when the activity is destroyed and restarted) and let it be the caller's responsibility to re-instantiate it.
- On the device go to "Developer Options" -> "Don't keep activities"
- Open a fresh install so the terms can be shown
- Click the home button to let the app go to the background or any link in the dialog
- Re-open the app
- Make sure it does **not** crash.
=> FE-1608 Hotfix/fix crashes

app/src/main/java/com/weatherxm/ui/common/DevicesAdapter.kt
A **UI** bug that didn't update the relation of a device when clicking "follow" or "unfollow".
In the `DeviceAdapter` also consider `device.relation` to reflect changes in the UI or not.
Follow & unfollow stations from a cell's list and make sure the UI updates correctly.
=> Update the relation in the UI when following a station from a cell's list

app/src/main/java/com/weatherxm/ui/widgets/currentweather/CurrentWeatherWidget.kt, app/src/main/java/com/weatherxm/ui/widgets/currentweather/CurrentWeatherWidgetDetailed.kt, app/src/main/java/com/weatherxm/ui/widgets/currentweather/CurrentWeatherWidgetTile.kt, app/src/main/java/com/weatherxm/ui/widgets/currentweather/CurrentWeatherWidgetWorkerUpdate.kt
Widgets fails to load after clearing app data on Android
Created `clearAllWidgets` in the Worker which is responsible for getting the widget IDs and sending "Should Select Station" events to them.
1. Add a widget
2. Close the app and clear its cache & data
3. Open the app
4. Ensure the widget is at the "Select Station" state
5. Login through the app
6. Select a station through the widget
7. Ensure everything looks OK.
Current limitations: Works only for 1 widget currently.
=> Reset widget to 'Select Station' when clear app data takes place

app/src/main/java/com/weatherxm/ui/devicesettings/BaseDeviceSettingsActivity.kt, app/src/main/java/com/weatherxm/ui/devicesettings/BaseDeviceSettingsViewModel.kt, app/src/main/java/com/weatherxm/ui/devicesettings/helium/DeviceSettingsHeliumActivity.kt, app/src/main/java/com/weatherxm/ui/devicesettings/wifi/DeviceSettingsWifiActivity.kt
Multiple code duplicates, try having a parent activity that will encapsulate most of the UI-related code in order to centralize it.
Create `BaseDeviceSettingsActivity` in order to capture most of the code that can be reused between the WiFi and Helium activities. Those two activities (`DeviceSettingsWifiActivity` and `DeviceSettingsHeliumActivity`) extend the `BaseDeviceSettingsActivity`.
Play around with both WiFi and Helium station settings and make sure everything is working properly and nothings has broken.
=> Optimizations in Device Settings Activities

app/src/local/assets/mock_files/get_device_rewards.json, app/src/main/java/com/weatherxm/data/models/ApiModels.kt, app/src/main/java/com/weatherxm/ui/components/compose/DailyRewardsView.kt, app/src/main/java/com/weatherxm/ui/rewarddetails/RewardDetailsActivity.kt, app/src/main/java/com/weatherxm/util/Rewards.kt
Hide warning banner when stations has 99% score
Created `shouldShowAnnotations` functions in the respective models and call them before showing any annotations.
Play with mock `get_device_rewards.json` and `get_device_reward_details.json` and ensure the annotations are not shown when reward or QoD score is 99% or 100%.
=> Hide info annotation banner on rewards when reward score is >=99%

app/src/main/java/com/weatherxm/ui/photoverification/gallery/PhotoGalleryActivity.kt, app/src/main/java/com/weatherxm/ui/photoverification/gallery/PhotoGalleryViewModel.kt, app/src/main/res/layout/activity_photo_gallery.xml, app/src/test/java/com/weatherxm/ui/photoverification/gallery/PhotoGalleryViewModelTest.kt
On Delete photo -> wait for API response before deleting it from Gallery
Wait for API before deleting a remote photo. also add linear loader and snackbar in case of error.
Perform photo deletions and ensure everything looks OK with/without error (e.g. with error = no connection or replace an argument in `usecase.deleteDevicePhoto` in the ViewModel's call place with an invalid one).
=> On Delete photo -> wait for API response before deleting it from Gallery

app/src/main/java/com/weatherxm/ui/components/compose/TermsDialog.kt
Fix background color of terms dialog in dark mode
`MaterialTheme.colorScheme.surface` ---> `colorResource(R.color.colorSurface)`
Check that it looks OK in both themes.
=> Fix background color of terms dialog in dark mode

app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt, app/src/main/java/com/weatherxm/ui/photoverification/gallery/PhotoGalleryActivity.kt, app/src/main/java/com/weatherxm/ui/photoverification/intro/PhotoVerificationIntroActivity.kt
Add screen view events in station photo verification
1. "Station Photos Instructions"  - For the instructions screen when terms are NOT visible.
2. "Station Photos Intro"  - For the instructions screen when terms are visible, e.g. on the first time we open this screen.
3. "Station Photos Gallery" - For the gallery screen
Ensure that events are logged properly.
=> Add screen view events in station photo verification

app/src/main/java/com/weatherxm/ui/widgets/currentweather/CurrentWeatherWidget.kt, app/src/main/java/com/weatherxm/ui/widgets/currentweather/CurrentWeatherWidgetDetailed.kt, app/src/main/java/com/weatherxm/ui/widgets/currentweather/CurrentWeatherWidgetTile.kt
There were some weird cases of widgets getting in an "empty"/undefined state in some cases (e.g. when clearing cache + data of the app). In this PR we are fixing this.
Remove `super.onReceive` from our 3 widgets so all the updates in our code take place through our custom overrides in `onReceive`.
Check the states of a widget(s) and ensure everything is OK, e.g.:
1. Showing the weather
2. Logged out
3. Delete a widget
4. Add widgets and then clear the app's data & cache 
5. Add a widget of a favorite station and then unfollow it
=> Remove super.onReceive from our 3 widgets.

app/src/main/java/com/weatherxm/data/datasource/DeviceOTADataSource.kt, app/src/main/java/com/weatherxm/data/models/Failure.kt, app/src/main/java/com/weatherxm/ui/claimdevice/helium/frequency/ClaimHeliumFrequencyFragment.kt, app/src/main/java/com/weatherxm/ui/components/HeliumSetFrequencyView.kt
Catch two obvious crashes in OTA and Change Frequency
1. Catch `IOException` that the `bytes()` function might throw.
2. Do not fire the `onSet` listener when the selected item position is `INVALID_POSITION == -1` (i.e. a frequency NOT selected yet)
Not sure, I didn't manage to reproduce either of them. You can try to reproduce the second one by commenting out the line 77 in `ChangeFrequencyViewModel`, no idea how a user has actually reproduced it though. I fixed the end result of it.
=> Catch two obvious crashes in OTA and Change Frequency

app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt, app/src/main/java/com/weatherxm/ui/photoverification/gallery/PhotoGalleryActivity.kt
1. Needs to split "Add Photo event to two events.
2. Add Photo doesn't seem to be clicked automatically 100% when gallery is empty
1. Added the `ACTION` param with values `STARTED` and `COMPLETED` for each different action (before and after photo is taken).
2. Fixed the listener when photos are empty at `onCreate`
1. Ensure both events are logged properly
2. Ensure that camera opens automatically when the gallery is empty and user has already accepted the permissons.
=> FE-1708 FE-1707 Fixes on "Add Photo" button

app/src/main/java/com/weatherxm/ui/home/HomeActivity.kt
Fetch banners whenever user returns to the device list
Ensure that the promotional banner is visible when going to the map or the profile and return to the devices list.
=> Pro promotional banner not visible when you go to map

app/src/main/java/com/weatherxm/ui/devicedetails/DeviceDetailsActivity.kt
Select content event on `Click on Chips` is tracked always instead of only when a click happens in the chips.
Moved the respective code inside the click listener.
Ensure the event is tracked ONLY on click on the chips.
=> Track "Click on Chips" select content event only on chip click

app/src/main/java/com/weatherxm/ui/cellinfo/CellInfoActivity.kt, app/src/main/res/values/strings.xml
Added no active stations chip in cell details when there aren't any.
Just use the existing code and instead of hiding the chip when there aren't any active stations, edit its text and background color.
Check some cells with and without active stations and ensure everything looks OK.
=> Added no active stations chip in cell details

app/src/main/java/com/weatherxm/ui/components/BaseMapFragment.kt, app/src/main/java/com/weatherxm/ui/explorer/ExplorerMapFragment.kt, app/src/main/java/com/weatherxm/ui/explorer/ExplorerViewModel.kt, app/src/main/java/com/weatherxm/ui/explorer/UIModels.kt, app/src/main/java/com/weatherxm/util/MapboxUtils.kt, app/src/test/java/com/weatherxm/ui/explorer/ExplorerViewModelTest.kt
Add station count labels to cells on map
- Created `pointManager` and utilized that in order to add points to the cells at zoom level >= 10.
- Also created function `toPointAnnotationOptions` that gives back all the point annotations that should be added in the map in a correct way, and added those points at the UI Model `ExplorerData` to serve them directly.
Ensure that everything looks and works OK with no lags.
=> Add station count labels to cells on map

app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt, app/src/main/java/com/weatherxm/ui/photoverification/gallery/PhotoGalleryActivity.kt
Use the correct source param for analytics. 
Should have the param in lowercase as `source`
=> Use the correct source param for analytics

.github/dependabot.yml, .github/workflows/on-assign-reviewer-pr.yml
Dependabot drops support for reviewers configuration option.
Created a new workflow that automatically assigns me as a reviewer on the PRs that I'm not the author (e.g. Dependabot or any community ones).
Not testable atm as it needs to be merged on main.
=> Automatically assign reviewer on PR

app/src/main/AndroidManifest.xml, app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt, app/src/main/java/com/weatherxm/ui/Navigator.kt, app/src/main/java/com/weatherxm/ui/common/Contracts.kt, app/src/main/java/com/weatherxm/ui/networkstats/NetworkStatsActivity.kt, app/src/main/java/com/weatherxm/ui/networkstats/UIModels.kt, app/src/main/java/com/weatherxm/ui/networkstats/tokenmetrics/TokenMetricsActivity.kt, app/src/main/res/layout/activity_network_stats.xml, app/src/main/res/layout/activity_token_metrics.xml, app/src/main/res/values/strings.xml
The existing $WXM Token card with the change that it should be moved in the Token Metrics screen. Also, change the color of the Circulating Supply bar 
- Create `TokenMetricsActivity` with the "$WXM Token" card, which opens when the "$WXM Rewards" card is clicked.
- Removed that card from the previous network stats activity.
- Moved the "Buy a station" prompt in network stats **above** the "$WXM Rewards".
Describe the testing process or steps taken to verify the changes made in this pull request.
Add any other context about the PR here or remove this section.
=> Create TokenMetricsActivity and its respective layout

app/src/main/java/com/weatherxm/ui/components/BaseMapFragment.kt, app/src/main/java/com/weatherxm/ui/explorer/ExplorerMapFragment.kt, app/src/main/java/com/weatherxm/ui/explorer/ExplorerViewModel.kt, gradle/libs.versions.toml
Support 16KB pages of Android 15.
- Added the respective `-ndk27` versions of our mapbox libraries.
- Also used the new `minZoom` param in `PointManager` of the newest version of Mapbox.
Create an emulator of 16KB page size and ensure it compiles and launches correctly.
=> Support 16KB pages of Android 15

app/src/main/java/com/weatherxm/ui/Navigator.kt, app/src/main/java/com/weatherxm/ui/components/ProPromotionDialogFragment.kt
Open Pro App in an external browser
Created an `openWebsiteExternally` function in `Navigator` and used that for opening the Pro.
For some reason the emulator crashes when testing it on my Windows, in any case feel free to give it a try, it may be specific to my system. Works OK in a physical device so if you have one please test it there.
=> Open Pro App in an external browser

app/src/main/java/com/weatherxm/analytics/MixpanelAnalyticsService.kt, app/src/test/java/com/weatherxm/analytics/MixpanelAnalyticsServiceTest.kt
Fix too many opt-in events tracked, issue happening on Android where in the last month we have 278K events.
We check if the user is opted out with `mixpanelAPI.hasOptedOutTracking()` and only if that's true, we proceed with the `optInTracking`.
Open and close the app multiple times, on the dev flavor, ensure that in the events in Mixpanel Dev, only one Opt In is being shown.
=> Fix multiple $opt_in events in Mixpanel

app/src/main/java/com/weatherxm/analytics/AnalyticsService.kt, app/src/main/java/com/weatherxm/analytics/AnalyticsWrapper.kt, app/src/main/java/com/weatherxm/app/AnalyticsInitializer.kt, app/src/main/java/com/weatherxm/data/services/CacheService.kt, app/src/main/java/com/weatherxm/ui/forecastdetails/ForecastDetailsActivity.kt, app/src/main/java/com/weatherxm/ui/home/locations/LocationsFragment.kt, app/src/test/java/com/weatherxm/TestConfig.kt, app/src/test/java/com/weatherxm/analytics/AnalyticsWrapperTest.kt, app/src/test/java/com/weatherxm/data/services/CacheServiceTest.kt
The feature analytics as specified in the respective [Linear issue](https://linear.app/weatherxm/issue/FE-1923/feature-analytics).
- Integrated a new user property which shows the number of saved locations and is updated dynamically (the same way as all others such as `stationsOwn` does)
- Two new screen view events, one for the locations in the home screen and one for the location forecast details
- A new user action when a user saves a location, with the distinction between authenticated and unauthenticated
User Action: Saved a location
**API isn't currently ready, so if you want to test it you need to do it with the local mock flavor**. Just ensure that the events look OK.
=> Feature analytics

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/weatherxm/ui/Navigator.kt, app/src/main/java/com/weatherxm/ui/login/LoginActivity.kt, app/src/main/java/com/weatherxm/ui/login/LoginViewModel.kt, app/src/main/java/com/weatherxm/ui/updateprompt/UpdatePromptActivity.kt, app/src/main/res/values/company_info.xml, app/src/main/res/values/messages.xml, app/src/solana/res/values/company_info.xml, app/src/test/java/com/weatherxm/ui/login/LoginViewModelTest.kt
As of now, we were using auto-generated version names and version codes for our apps. In this PR a similar mechanism is introduced, but for Solana. Instead of using the current tags we use in our prod app, different tags will be used for Solana, only those starting with the prefix `Solana_` (such as, the already created `Solana_4.10.0` and `Solana_5.0.0`).
This ensures that Solana versions don't need to follow and/or match our production app's one and we don't have to create new releases in our prod app to match the Solana ones.
Also, conditional audiences have been created in the Firebase's Remote Config that target our Solana app.
So, in case of an update prompt is found, redirect the users to the Solana DApp Store.
In the `getVersionGitTags` and `getLastVersionGitTag`, we introduced …
=> Different handling of update prompts for Solana users.
